# SPDX-FileCopyrightText: 2025 Alexander Dahl <post@lespocky.de>
# SPDX-License-Identifier: CC0-1.0
---
name: Misc Checks

# yamllint disable-line rule:truthy
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  editorconfig:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: editorconfig-checker/action-editorconfig-checker@v2
      - run: editorconfig-checker

  hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: hadolint/hadolint-action@v3.3.0

  reuse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@v6
