# SPDX-FileCopyrightText: 2025 Alexander Dahl <post@lespocky.de>
# SPDX-License-Identifier: CC0-1.0
---
name: EditorConfig Checker

# yamllint disable-line rule:truthy
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  editorconfig:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: editorconfig-checker/action-editorconfig-checker@v2
      - run: editorconfig-checker
